name: CI

# Trigger on pushes and pull requests to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out your repository’s code
      - uses: actions/checkout@v3

      # Set up the Node.js environment
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - run: npm install

      # Run your unit tests
      - run: npm test -- --ci --reporters=default

      # Optionally build the app
      - run: npm run build
